#!/bin/sh

### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $local_fs $remote_fs $network $syslog
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts the tomcat web server
# Description: starts tomcat using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
START_DAEMON=/opt/activiti/bin/startup.sh
STOP_DAEMON=/opt/activiti/bin/shutdown.sh

NAME=activiti
DESC=activiti

set -e

#. /lib/lsb/init-functions

case "$1" in
start)
activiti_pid=`ps -ef | grep apache | grep tomcat | grep java | egrep -v grep | awk '{print $2}'`
if [ -n "$tomcat_pid" ]; then
echo "activiti is running."
exit 1;
fi
echo -n "Starting $DESC:\n $START_DAEMON \n"
$START_DAEMON
;;

stop)
activiti_pid=`ps -ef | grep apache | grep tomcat | grep java | egrep -v grep | awk '{print $2}'`
if [ -z "$activiti_pid" ]; then
echo "activiti is not running."
exit 1;
fi
echo -n "Stopping $DESC:\n $STOP_DAEMON \n "
$STOP_DAEMON
;;

restart|force-reload)
activiti_pid=`ps -ef | grep apache | grep tomcat | grep java | egrep -v grep | awk '{print $2}'`
if [ -n "$activiti_pid" ]; then
echo -n "Restarting $DESC: \n $STOP_DAEMON \n"
$STOP_DAEMON
sleep 5
fi
echo -n "starting $DESC: \n $START_DAEMON \n"
$START_DAEMON
echo "Starting, please wait for about 50 seconds."
sleep 20
;;

*)
echo "Usage: $NAME {start|stop|restart}" >&2
exit 1
;;
esac

exit 0